name: CI
on: [push, pull_request]

jobs:
  build-osx:
    runs-on: macos-latest
    steps:
      - run: brew update
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.macos
      - run: '[ -e subdivide/examples/ccsub ]'
      - run: '[ -e subdivide/examples/loopsub ]'
      - run: '[ -e subdivide/examples/subviewer ]'

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install freeglut3-dev
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.linux
      - run: '[ -e subdivide/examples/ccsub ]'
      - run: '[ -e subdivide/examples/loopsub ]'
      - run: '[ -e subdivide/examples/subviewer ]'
