name: CI
on: [push, pull_request]

jobs:
  build-osx:
    runs-on: macos-latest
    steps:
      - run: brew update
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.macos
      - name: Build Output Check
        if: |
          ${{ hashFiles('subdivide/examples/ccsub') == ''
           || hashFiles('subdivide/examples/loopsub') == ''
           || hashFiles('subdivide/examples/subviewer') == '' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Expected build outputs are missing')

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install freeglut3-dev
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.linux
