name: CI
on: [push, pull_request]

jobs:
  build-osx:
    runs-on: macos-latest
    steps:
      - run: brew update
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.macos
      - run: '[ -f subdivide/examples/ccsub ]'
      - run: '[ -f subdivide/examples/loopsub ]'
      - run: '[ -f subdivide/examples/subviewer ]'

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install freeglut3-dev
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.linux
      - run: '[ -f subdivide/examples/ccsub ]'
      - run: '[ -f subdivide/examples/loopsub ]'
      - run: '[ -f subdivide/examples/subviewer ]'

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.windows
      - run: 'If (!(Test-Path -Path "subdivide\examples\ccsub" -PathType Leaf)) { exit 1 }'
      - run: 'If (!(Test-Path -Path "subdivide\examples\loopsub" -PathType Leaf)) { exit 1 }'
      - run: 'If (!(Test-Path -Path "subdivide\examples\subviewer" -PathType Leaf)) { exit 1 }'
