name: CI
on: [push, pull_request]

jobs:
  build-osx:
    runs-on: macos-latest
    steps:
      - run: brew update
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.macos

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make -C subdivide -f Makefile.linux
