name: CI

on: [push, pull_request]

jobs:
  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew update
          brew install cmake
      - name: Configure with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Verify artifacts
        run: |
          ls -la build/subdivide/src/libsub.a
          [ -f build/subdivide/src/libsub.a ]

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++
      - name: Configure with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Verify artifacts
        run: |
          ls -la build/subdivide/src/libsub.a
          [ -f build/subdivide/src/libsub.a ]
