name: CI

on: [push, pull_request]

jobs:
  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew update
          brew install cmake freeglut
      - name: Configure with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Verify artifacts
        run: |
          # Verify libraries
          ls -la build/subdivide/src/libsub.a
          [ -f build/subdivide/src/libsub.a ]
          ls -la build/subdivide/viewer/libviewer.a
          [ -f build/subdivide/viewer/libviewer.a ]

          # Verify example binaries exist
          ls -la build/subdivide/examples/ccsub
          [ -f build/subdivide/examples/ccsub ]
          ls -la build/subdivide/examples/loopsub
          [ -f build/subdivide/examples/loopsub ]
          ls -la build/subdivide/examples/subviewer
          [ -f build/subdivide/examples/subviewer ]

      - name: Test CLI help commands
        run: |
          # Test each CLI with help flag
          echo "Testing ccsub --help"
          build/subdivide/examples/ccsub --help || build/subdivide/examples/ccsub -h

          echo "Testing loopsub --help"
          build/subdivide/examples/loopsub --help || build/subdivide/examples/loopsub -h

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ freeglut3-dev xvfb
      - name: Configure with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Verify artifacts
        run: |
          # Verify libraries
          ls -la build/subdivide/src/libsub.a
          [ -f build/subdivide/src/libsub.a ]
          ls -la build/subdivide/viewer/libviewer.a
          [ -f build/subdivide/viewer/libviewer.a ]

          # Verify example binaries exist
          ls -la build/subdivide/examples/ccsub
          [ -f build/subdivide/examples/ccsub ]
          ls -la build/subdivide/examples/loopsub
          [ -f build/subdivide/examples/loopsub ]
          ls -la build/subdivide/examples/subviewer
          [ -f build/subdivide/examples/subviewer ]

      - name: Test CLI help commands
        run: |
          # Test each CLI with help flag
          echo "Testing ccsub --help"
          build/subdivide/examples/ccsub --help || build/subdivide/examples/ccsub -h

          echo "Testing loopsub --help"
          build/subdivide/examples/loopsub --help || build/subdivide/examples/loopsub -h
